model: gpt2_ft_lora
model_dir: LLM_Cybersecurity_Summarizer/GPT2_Finetuning/lora_gpt2_finetune_outcome/best_model      # ← FT_GPT2_LORA_BEST_MODEL_DIR
data_file: LLM_Cybersecurity_Summarizer/DataPreprocessing/test.jsonl
lines: []                   # which example‑lines to sample
max_new_tokens: 100
evaluation_metric: rouge
output_dir: Evaluation_Results/Finetuned/GPT2_Results
