model: gpt2_local
model_dir: LLM_Cybersecurity_Summarizer/GPT2_GroundUp/Custom_Pretrained_GPT2_Finetuning_Outcome     # ← FT_GPT2_BEST_MODEL_DIR
data_file: LLM_Cybersecurity_Summarizer/DataPreprocessing/test.jsonl
lines: []                   # which example‑lines to sample
max_new_tokens: 100
evaluation_metric: rouge
output_dir: Evaluation_Results/Finetuned/GPT2_Results
