model: google/pegasus-xsum
data_file: LLM_Cybersecurity_Summarizer/DataPreprocessing/test.jsonl
lines: []
max_new_tokens: 100
evaluation_metric: rouge
output_dir: Evaluation_Results/ZeroShot/PEGASUS_Results 
